version: "3.5"

services:
    falafel:
        container_name: falafel
        build:
            context: ./falafel
            dockerfile: ./Dockerfile
        ports:
            - "80:80"
        depends_on:
            - "butter"
        env_file: './butter/production.env'
    butter:
        container_name: butter
        build:
            context: ./butter
            dockerfile: ./Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - "mango"
        env_file: './butter/production.env'
    mango:
        image: 'mongo:latest'
        env_file: './mongo.env'
        volumes: 
            #- oatdata:/data/db #actual volume for mongo
            - ./mango/data:/data/db #local file mongo
            - ./mango/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        ports:
            - '27017-27019:27017-27019'
        command: --auth
