version: "3.5"

services:    
    mongo:
        image: 'mongo:latest'
        env_file: './mongo.env'
        volumes: 
            - oatdata:/data/db
        ports:
            - '27017-27019:27017-27019'
        command: --auth
